// <auto-generated />
using System;
using ApotheGSF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApotheGSF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApotheGSF.Models.AppRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreNormalizado");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NombreNormalizado] IS NOT NULL");

                    b.ToTable("tblRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "07c491f0-be48-4705-a860-0f2e196497a8",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "65fce93a-9d0e-400f-a3c1-43d2b3f09569",
                            Name = "Comprador",
                            NormalizedName = "COMPRADOR"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "1a5e96fc-c165-48b6-b6c8-f58a93dec18a",
                            Name = "Vendedor",
                            NormalizedName = "VENDEDOR"
                        });
                });

            modelBuilder.Entity("ApotheGSF.Models.AppUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("ConfirmarEmail");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Foto");

                    b.Property<bool?>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EmailNormalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuarioNormalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("ConfirmarTelefono");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NombreUsuarioNormalizado] IS NOT NULL");

                    b.ToTable("tblUsuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Apellido = "",
                            ConcurrencyStamp = "47a14708-85df-4069-86d3-9078a8d6300a",
                            Creado = new DateTime(2022, 8, 9, 12, 41, 15, 452, DateTimeKind.Local).AddTicks(2220),
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactivo = false,
                            LockoutEnabled = true,
                            Modificado = new DateTime(2022, 8, 9, 12, 41, 15, 452, DateTimeKind.Local).AddTicks(2272),
                            Nombre = "Admin",
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEB6ZSLZ0yaEUn0tARYVJQ5pzHDUYcBNrw7imkPoiMZ74bLwrQO/5PQ4ZnBAk1IbgAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ApotheGSF.Models.AppUsuarioRol", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoUsuario");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoRol");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tblUsuariosRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ApotheGSF.Models.FacturaMedicamentosCajas", b =>
                {
                    b.Property<int>("CodigoFactura")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCaja")
                        .HasColumnType("int");

                    b.Property<int>("CantidadUnidad")
                        .HasColumnType("int");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<int>("TipoCantidad")
                        .HasColumnType("int");

                    b.HasKey("CodigoFactura", "CodigoCaja");

                    b.HasIndex("CodigoCaja");

                    b.ToTable("tblFacturasMedicamentosCajas", (string)null);
                });

            modelBuilder.Entity("ApotheGSF.Models.Facturas", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<DateTime?>("Creado")
                        .HasColumnType("datetime")
                        .HasColumnName("Creado");

                    b.Property<string>("CreadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("Codigo");

                    b.ToTable("tblFacturas", (string)null);
                });

            modelBuilder.Entity("ApotheGSF.Models.Medicamentos", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concentracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Costo")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Creado")
                        .HasColumnType("datetime")
                        .HasColumnName("Creado");

                    b.Property<string>("CreadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EnvioPendiente")
                        .HasColumnType("bit");

                    b.Property<bool?>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<float>("PrecioUnidad")
                        .HasColumnType("real");

                    b.Property<string>("Sustancia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesCaja")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("tblMedicamentos", (string)null);
                });

            modelBuilder.Entity("ApotheGSF.Models.MedicamentosCajas", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<int>("CantidadUnidad")
                        .HasColumnType("int");

                    b.Property<int>("CodigoMedicamento")
                        .HasColumnType("int");

                    b.Property<bool>("Detallada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAdquirido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Inactivo")
                        .HasColumnType("bit");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoMedicamento");

                    b.ToTable("tblMedicamentosCajas", (string)null);
                });

            modelBuilder.Entity("ApotheGSF.Models.Proveedores", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<DateTime?>("Creado")
                        .HasColumnType("datetime")
                        .HasColumnName("Creado");

                    b.Property<string>("CreadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoNombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminosdePago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("tblProveedores", (string)null);
                });

            modelBuilder.Entity("ApotheGSF.Models.ProveedorMedicamentos", b =>
                {
                    b.Property<int>("CodigoMedicamento")
                        .HasColumnType("int");

                    b.Property<int>("CodigoProveedor")
                        .HasColumnType("int");

                    b.HasKey("CodigoMedicamento", "CodigoProveedor");

                    b.HasIndex("CodigoProveedor");

                    b.ToTable("tblProveedoresMedicamentos", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoClaim");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorClaim");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoRol");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tblRolClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoClaim");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorClaim");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoUsuario");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblUsuarioClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoUsuario");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("tblUsuarioLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoUsuario");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Valor");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("tblUsuarioToken", (string)null);
                });

            modelBuilder.Entity("ApotheGSF.Models.AppUsuarioRol", b =>
                {
                    b.HasOne("ApotheGSF.Models.AppRol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApotheGSF.Models.AppUsuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApotheGSF.Models.FacturaMedicamentosCajas", b =>
                {
                    b.HasOne("ApotheGSF.Models.MedicamentosCajas", "MedicamentosCajas")
                        .WithMany("FacturaMedicamentos")
                        .HasForeignKey("CodigoCaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApotheGSF.Models.Facturas", "Facturas")
                        .WithMany("FacturasMedicamentosCajas")
                        .HasForeignKey("CodigoFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facturas");

                    b.Navigation("MedicamentosCajas");
                });

            modelBuilder.Entity("ApotheGSF.Models.MedicamentosCajas", b =>
                {
                    b.HasOne("ApotheGSF.Models.Medicamentos", "Medicamentos")
                        .WithMany("MedicamentosCajas")
                        .HasForeignKey("CodigoMedicamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("ApotheGSF.Models.ProveedorMedicamentos", b =>
                {
                    b.HasOne("ApotheGSF.Models.Medicamentos", "Medicamentos")
                        .WithMany("ProveedoresMedicamentos")
                        .HasForeignKey("CodigoMedicamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApotheGSF.Models.Proveedores", "Proveedores")
                        .WithMany("ProveedoresMedicamentos")
                        .HasForeignKey("CodigoProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamentos");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ApotheGSF.Models.AppRol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ApotheGSF.Models.AppUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ApotheGSF.Models.AppUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ApotheGSF.Models.AppUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApotheGSF.Models.AppRol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("ApotheGSF.Models.AppUsuario", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("ApotheGSF.Models.Facturas", b =>
                {
                    b.Navigation("FacturasMedicamentosCajas");
                });

            modelBuilder.Entity("ApotheGSF.Models.Medicamentos", b =>
                {
                    b.Navigation("MedicamentosCajas");

                    b.Navigation("ProveedoresMedicamentos");
                });

            modelBuilder.Entity("ApotheGSF.Models.MedicamentosCajas", b =>
                {
                    b.Navigation("FacturaMedicamentos");
                });

            modelBuilder.Entity("ApotheGSF.Models.Proveedores", b =>
                {
                    b.Navigation("ProveedoresMedicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
